version: "3.9"

services:
  nocthera:
    container_name: nocthera
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./backups:/app/backups
      - ./temp:/app/temp
    ports:
      - "3000:3000"