services:
  - type: worker
    name: nocthera
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: OWNER_ID
        sync: false
